import dotenv
import os
from typing import Final

BQ_PROJECT_ID = os.environ['BQ_PROJECT_ID']
PROJECT_DATASET = os.environ['PROJECT_DATASET']

# FQTN: Fully Qualified Table Name
APPOINTMENTS_FQTN: Final = f"`{BQ_PROJECT_ID}.{PROJECT_DATASET}.{os.environ['APPOINTMENTS_TABLE']}`"
DEPARTMENTS_FQTN: Final = f"`{BQ_PROJECT_ID}.{PROJECT_DATASET}.{os.environ['DEPARTMENTS_TABLE']}`"
HOSPITALS_FQTN: Final = f"`{BQ_PROJECT_ID}.{PROJECT_DATASET}.{os.environ['HOSPITALS_TABLE']}`"
WAITLIST_FQTN: Final = f"`{BQ_PROJECT_ID}.{PROJECT_DATASET}.{os.environ['WAITLIST_TABLE']}`"
REJECTED_APPOINTMENTS_FQTN: Final = f"`{BQ_PROJECT_ID}.{PROJECT_DATASET}.{os.environ['REJECTED_APPOINTMENTS_TABLE']}`"